https://numpy.org/doc/stable/user/quickstart.html


## Numpy

Numpy, which stand for Numerical Python, it is a python package used for scientific computation. It allows users to perform fast operations related to mathematics, arrays, linear algebra, statistics and more. It is an efficient tool for shape manipulation, sorting, and selecting elements. 


### Numpy ndarray
Reference:

    1- https://www.geeksforgeeks.org/difference-between-list-and-array-in-python/ 
    2- Vanderplas, Python Data Science Handbook: Tools and techniques for developers 2016

- Numpy ndarray stands for N dimentional array, it is a class of Numpy's array which has attributes such as ndim, shape, size, dtype, itemsize, data
- The elements inside the array are made of the same data type and with the same size in memory
- Numpy array are fixed size when created, if one decided to change the size then a new array is created and the original is  deleted
- It is possible to have arrays of objects, which can be made of different sized elements 
- While NumPy arrays share some similarities with Python's List container, they offer much more efficient storage and data handling experience when dealing with large set of data.
- Difference between list and numpy array is that a List can contain elements of different size and data type
- Mathematical operations cannot be directly performed with List
- No Looping is required to print out the entire List
- In List slices are copies and array slices are views


### Creating Array

In [2]:
import numpy as np

In [3]:
#Creating an array using Range()
a = np.array(range(1,10))
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
# Creating an array using Numpy random number generator

np.random.seed(0) # same random number is generated when the code is run
a2 = np.random.randint(6, size = 7)
a3 = np.random.randint(6, size = (3,4))
a4 = np.random.randint(6, size = (3,4,5))
a4

array([[[1, 5, 0, 1, 4],
        [3, 0, 3, 5, 0],
        [2, 3, 0, 1, 3],
        [5, 3, 3, 0, 1]],

       [[1, 1, 0, 2, 4],
        [3, 3, 2, 4, 2],
        [0, 0, 4, 5, 5],
        [0, 4, 1, 4, 1]],

       [[2, 2, 0, 1, 1],
        [1, 1, 3, 3, 2],
        [3, 0, 3, 5, 4],
        [1, 2, 4, 3, 4]]])

In [5]:
# Creating an array using list
x = np.array([3, 4, 5, 8])
x

array([3, 4, 5, 8])

In [6]:
# Creating arrays of zeros with zero() function
a_zero = np.zeros(6) # 1-dimensional array of zero
print(a_zero)
print('\n')
a2_zero = np.zeros((3,4)) # 2-dimensional array of zero
print(a2_zero)

[0. 0. 0. 0. 0. 0.]


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [7]:
# Creating arrays of ones using ones() function

a_ones = np.ones(6)
a2_ones = np.ones((4,5))
print(a_ones)
print('\n')
print(a2_ones)

[1. 1. 1. 1. 1. 1.]


[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [8]:
# Creating an eye array with eye() function

eye= np.eye(3)
eye

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Array Attributes

- Dtypes Attribute: Arrays can have a variety of data types, as shown in the table below. The dtype keyword identifies the type of data the array contains. 
- Ndim: represent the number of dimensions, it can one or multi-dimensional array
- Shape: it is shown by a tuple of integers, which indicate the number of rows and columns.
- Size: represents the total number of elements in an array, which is the product of the elements of shape. 
- Itemsize: The size in bytes of each element in an array

In [9]:
a4

array([[[1, 5, 0, 1, 4],
        [3, 0, 3, 5, 0],
        [2, 3, 0, 1, 3],
        [5, 3, 3, 0, 1]],

       [[1, 1, 0, 2, 4],
        [3, 3, 2, 4, 2],
        [0, 0, 4, 5, 5],
        [0, 4, 1, 4, 1]],

       [[2, 2, 0, 1, 1],
        [1, 1, 3, 3, 2],
        [3, 0, 3, 5, 4],
        [1, 2, 4, 3, 4]]])

In [10]:
a4.dtype

dtype('int32')

In [11]:
a4.ndim

3

In [12]:
a4.shape

(3, 4, 5)

In [13]:
a4.size

60

In [14]:
a4.itemsize

4

In [15]:
# As arrays can only be made of the same data type, when they are made from different types of data, Numpy upcasts whenever it is possible, 
# meaning it will convert the type for consistency purposes. In the example below, the original list the type was mixed of float and int
# the output is float only. 

x1 = np.array([1.1 ,3 , 4, 8])
x1

array([1.1, 3. , 4. , 8. ])

### Indexing

In [16]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
a[0] # the first element of a

1

In [18]:
a[5] # the sixth element

6

In [19]:
a[-1] # the last element

9

In [20]:
a[-3] # the third last

7

In [21]:
# In case of higher dimension array ',' seperates the rows and columns

a3

array([[3, 5, 2, 4],
       [0, 0, 4, 2],
       [1, 0, 1, 5]])

In [22]:
a3[0,0] # Selects the value in first row and first column

3

In [23]:
a3[1,3] # selects the value in second row and fourth colum

2

In [24]:
a3[2,3] # selects the value in third row and fourth colum

5

In [25]:
a3[2,-1] # same result as the above, since -1 represent the last column

5

### Slicing

In [26]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
# a[start:stop:step]
# start is the starting index
# stop is stopping index
# step is the step in between, which starts at 1
a[::1]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
a[::2] # Selecting every other element

array([1, 3, 5, 7, 9])

In [29]:
# The elements are reversed, meaning it starts at the end all the way to the first element, 
# Negative indices are interpreted as counting from the end of the array

a[::-1] 

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

In [30]:
a[6::-1] # Starting at 7th element, it goes down by 1

array([7, 6, 5, 4, 3, 2, 1])

In [31]:
a[-3:10] # Starting at the third last element and move up by one 

array([7, 8, 9])

In [32]:
a[-2:4:-1] # Starting at the second last element goes down by one until the fifth element(which is not included)

array([8, 7, 6])

### Slicing Multidimentional Array

In [33]:
x = np.array([[1,2,3], [4,5,6],[7,8,9],[10,11,12]])
x

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [34]:
# selecting the first 4 rows and 2 columns
# Note that to choose the second column, we need to set the stopping index as 2 which is not included, 
# one might think of x[:,:1], however, the stopping index is not included, that is why we set it equal to 2.

x[:,:2]

array([[ 1,  2],
       [ 4,  5],
       [ 7,  8],
       [10, 11]])

In [35]:
x[:2,1:3]

array([[2, 3],
       [5, 6]])

In [36]:
x[2:4, 1:3]

array([[ 8,  9],
       [11, 12]])

In [37]:
x[1:3, :2]

array([[4, 5],
       [7, 8]])

In [38]:
# Selecting 4 rows and every other column
x[:,::2] 

array([[ 1,  3],
       [ 4,  6],
       [ 7,  9],
       [10, 12]])

In [39]:
# Reversing the dimensions 

print(x[::-1, ::-1])
print("\n")
print(x)


[[12 11 10]
 [ 9  8  7]
 [ 6  5  4]
 [ 3  2  1]]


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


### Subarrays Views

You should note that array slices return views of data rather than copies, meaning if part of an array is selected and modified, the original array will also be modified

In [40]:
a3

array([[3, 5, 2, 4],
       [0, 0, 4, 2],
       [1, 0, 1, 5]])

In [41]:
a_mod = a3[:, 1:3] # Selecting a part of a3 and load it to a_mod
a_mod

array([[5, 2],
       [0, 4],
       [0, 1]])

In [42]:
a_mod[2:3,0] = 1 # Changed the value in third row and first column to 1
a_mod

array([[5, 2],
       [0, 4],
       [1, 1]])

In [43]:
a3 # Now the content of the original a3 has changed as well

array([[3, 5, 2, 4],
       [0, 0, 4, 2],
       [1, 1, 1, 5]])

### Creating copies of arrays

When is needed to work with part of an array without changing the content of the original one, we can use the copy() method to copy it in a seperate variable.

In [44]:
a3

array([[3, 5, 2, 4],
       [0, 0, 4, 2],
       [1, 1, 1, 5]])

In [45]:
a_copy = a3[:, 1:3].copy()
a_copy

array([[5, 2],
       [0, 4],
       [1, 1]])

In [46]:
a_copy[:1,:] = 6
a_copy

array([[6, 6],
       [0, 4],
       [1, 1]])

In [47]:
a3 # Since we copied a part of a3 to a seperate variable, changing the content of a_copy did not affect a3

array([[3, 5, 2, 4],
       [0, 0, 4, 2],
       [1, 1, 1, 5]])

### Reshaping of Arrays

Consider a one-dimensional array you wish to transform into a 3x3 matrix. A convenient way of doing so is using the reshape() method. Note that the size of the transformed array must be the same as the original one.

In [48]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
a.shape

(9,)

In [50]:
a_matrix = a.reshape(3,3) # transforming a 1-d array to 3x3 matrix
a_matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [51]:
a_matrix.shape

(3, 3)

### Adding a New Dimension

It is also possible to add a new dimension by using np.newaxis in a slice operation. 


In [52]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [53]:
a_2d = a[np.newaxis,:] 
a_2d

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [54]:
a_2d.shape # 1 row and 9 columns

(1, 9)

In [55]:
a_2d_column = a[:,np.newaxis]
a_2d_column

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [56]:
a_2d_column.shape # 9 row and 1 column

(9, 1)

### Concatenation and Splitting

Joining two or more arrays using the following routines:

    - np.concatenate
    - np.vstack (vertical stack)
    - np.hstack (horizontal stack)
 

In [60]:
a = np.array([0,1,2])
b = np.array([3,4,5])

np.concatenate((a,b)) # adding two arrays 

array([0, 1, 2, 3, 4, 5])

In [61]:
c = [6,7,8]

In [62]:
np.concatenate((a,b,c))

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [66]:
# adding 2-D array

array_2d = np.array([[1,2,3],[4,5,6]])
array_2d

array([[1, 2, 3],
       [4, 5, 6]])

In [67]:
np.concatenate((array_2d, array_2d)) # adding arrays of same dimension vertically

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [68]:
np.concatenate((array_2d,array_2d), axis = 1) # adding arrays of same dimension horizontally

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [69]:
a = [7,8,9]

np.concatenate((a,array_2d)) # cannot add two arrays of different dimension using np.concatenate

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 2 dimension(s)

In [70]:
np.vstack((a,array_2d)) # adding arrays of different dimension with same number of columns vertically

array([[7, 8, 9],
       [1, 2, 3],
       [4, 5, 6]])

In [74]:
a = np.array([1,2])

np.vstack((a,array_2d)) # cannot add them because they have different sizes

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 2 and the array at index 1 has size 3

In [84]:
a1 = np.array([1,2,3])

In [85]:
a1.shape

(3,)

In [86]:
a1.size

3

In [77]:
array_2d[0].size

3

In [88]:
# since a1 have 1 row with size 3 and array_2d has two 
#rows each with size 3 then it is possible to add them vertically

np.vstack((a1,array_2d)) 

array([[1, 2, 3],
       [1, 2, 3],
       [4, 5, 6]])

In [89]:
a2 = np.array([1,2])

In [90]:
np.hstack((a2,array_2d)) # cannot add them horizontally due different dimensions

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 2 dimension(s)

In [93]:
a3 = np.array([[1,2,3],[4,5,6]]) # 2-dimensional array

In [94]:
np.hstack((a3,array_2d)) # it is possible to add them horizontally since they are both 2-D

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

### Splitting of Array

In [95]:
# the first argument n is the array that we want to split,the second argument [] tells us how it is divided
# [3,5]--> n[:3] = [1,2,3], then n[3:5] = [4,5], and the rest n[5:] = [6, 7, 7, 8]

n = [1,2,3,4,5,6,7,7,8]
np.split(n, [3, 5])

[array([1, 2, 3]), array([4, 5]), array([6, 7, 7, 8])]

In [100]:
array = np.arange(12).reshape((3,4))
array

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [103]:
np.vsplit(array,[2])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]])]

In [104]:
np.hsplit(array,[2])

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

### Computation on Numpy Arrays