https://numpy.org/doc/stable/user/quickstart.html


## Numpy

Numpy, which stand for Numerical Python, it is a python package used for scientific computation. It allows users to perform fast operations related to mathematics, arrays, linear algebra, statistics and more. It is an efficient tool for shape manipulation, sorting, and selecting elements. 


### Numpy ndarray
Reference:
1- https://www.geeksforgeeks.org/difference-between-list-and-array-in-python/
2- Vanderplas, Python Data Science Handbook: Tools and techniques for developers 2016

- Numpy ndarray stands for N dimentional array, it is a class of Numpy's array which has attributes such as ndim, shape, size, dtype, itemsize, data
- The elements inside the array are made of the same data type and with the same size in memory
- Numpy array are fixed size when created, if one decided to change the size then a new array is created and the original is  deleted
- It is possible to have arrays of objects, which can be made of different sized elements 
- While NumPy arrays share some similarities with Python's List container, they offer much more efficient storage and data handling experience when dealing with large set of data.
- Difference between list and numpy array is that a List can contain elements of different size and data type
- Mathematical operations cannot be directly performed with List
- No Looping is required to print out the entire List


### Creating Array

In [2]:
import numpy as np

In [3]:
#Creating an array using Range()
a = np.array(range(1,10))
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
# Creating an array using Numpy random number generator

np.random.seed(0) # same random number is generated when the code is run
a2 = np.random.randint(6, size = 7)
a3 = np.random.randint(6, size = (3,4))
a4 = np.random.randint(6, size = (3,4,5))
a4

array([[[1, 5, 0, 1, 4],
        [3, 0, 3, 5, 0],
        [2, 3, 0, 1, 3],
        [5, 3, 3, 0, 1]],

       [[1, 1, 0, 2, 4],
        [3, 3, 2, 4, 2],
        [0, 0, 4, 5, 5],
        [0, 4, 1, 4, 1]],

       [[2, 2, 0, 1, 1],
        [1, 1, 3, 3, 2],
        [3, 0, 3, 5, 4],
        [1, 2, 4, 3, 4]]])

In [53]:
# Creating an array using list
x = np.array([3, 4, 5, 8])
x

array([3, 4, 5, 8])

### Array Attributes

- Dtypes Attribute: Arrays can have a variety of data types, as shown in the table below. The dtype keyword identifies the type of data the array contains. 
- Ndim: represent the number of dimensions, it can one or multi-dimensional array
- Shape: it is shown by a tuple of integers, which indicate the number of rows and columns.
- Size: represents the total number of elements in an array, which is the product of the elements of shape. 
- Itemsize: The size in bytes of each element in an array

In [62]:
a4

array([[[1, 5, 0, 1, 4],
        [3, 0, 3, 5, 0],
        [2, 3, 0, 1, 3],
        [5, 3, 3, 0, 1]],

       [[1, 1, 0, 2, 4],
        [3, 3, 2, 4, 2],
        [0, 0, 4, 5, 5],
        [0, 4, 1, 4, 1]],

       [[2, 2, 0, 1, 1],
        [1, 1, 3, 3, 2],
        [3, 0, 3, 5, 4],
        [1, 2, 4, 3, 4]]])

In [63]:
a4.dtype

dtype('int32')

In [64]:
a4.ndim

3

In [65]:
a4.shape

(3, 4, 5)

In [66]:
a4.size

60

In [67]:
a4.itemsize

4

In [68]:
# As arrays can only be made of the same data type, when they are made from different types of data, Numpy upcasts whenever it is possible, 
# meaning it will convert the type for consistency purposes. In the example below, the original list the type was mixed of float and int
# the output is float only. 

x1 = np.array([1.1 ,3 , 4, 8])
x1

array([1.1, 3. , 4. , 8. ])

### Indexing

In [69]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [71]:
a[0] # the first element of a

1

In [72]:
a[5] # the sixth element

6

In [74]:
a[-1] # the last element

9

In [75]:
a[-3] # the third last

7

In [78]:
# In case of higher dimension array ',' seperates the rows and columns

a3

array([[3, 5, 2, 4],
       [0, 0, 4, 2],
       [1, 0, 1, 5]])

In [79]:
a3[0,0] # Selects the value in first row and first column

3

In [80]:
a3[1,3] # selects the value in second row and fourth colum

2

In [82]:
a3[2,3] # selects the value in third row and fourth colum

5

In [83]:
a3[2,-1] # same result as the above, since -1 represent the last column

5

### Slicing

In [84]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [85]:
# a[start:stop:step]
# start is the starting index
# stop is stopping index
# step is the step in between, which starts at 1
a[::1]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
a[::2] # Selecting every other element

array([1, 3, 5, 7, 9])

In [17]:
# The elements are reversed, meaning it starts at the end all the way to the first element, 
# Negative indices are interpreted as counting from the end of the array

a[::-1] 

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

In [10]:
a[6::-1] # Starting at 7th element, it goes down by 1

array([7, 6, 5, 4, 3, 2, 1])

In [11]:
a[-3:10] # Starting at the third last element and move up by one 

array([7, 8, 9])

In [12]:
a[-2:4:-1] # Starting at the second last element goes down by one until the fifth element(which is not included)

array([8, 7, 6])

### Slicing Two Dimentional Array

In [16]:
x = np.array([[1,2,3], [4,5,6]])
x

array([[1, 2, 3],
       [4, 5, 6]])

In [91]:
x = np.array([1, 2, 3])
# row vector via reshape
#x.reshape((1, 3))
x

array([1, 2, 3])

In [92]:
x.shape

(3,)

In [95]:
x[np.newaxis,:]

array([[1, 2, 3]])

In [96]:
x[:,np.newaxis]

array([[1],
       [2],
       [3]])