## Numpy

### Slicing 1-D Array

In [1]:
import numpy as np

In [5]:
a = np.array(range(1,10))
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
# a[start:stop:step]
# start is the starting index
# stop is stopping index
# step is the step in between, which starts at 1
a[::1]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
a[::2] # Selecting every other element

array([1, 3, 5, 7, 9])

In [17]:
# The elements are reversed, meaning it starts at the end all the way to the first element, 
# Negative indices are interpreted as counting from the end of the array

a[::-1] 

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

In [10]:
a[6::-1] # Starting at 7th element, it goes down by 1

array([7, 6, 5, 4, 3, 2, 1])

In [11]:
a[-3:10] # Starting at the third last element and move up by one 

array([7, 8, 9])

In [12]:
a[-2:4:-1] # Starting at the second last element goes down by one until the fifth element(which is not included)

array([8, 7, 6])

### Slicing Two Dimentional Array

In [16]:
x = np.array([[1,2,3], [4,5,6]])
x

array([[1, 2, 3],
       [4, 5, 6]])