https://numpy.org/doc/stable/user/quickstart.html


## Numpy

Numpy, which stand for Numerical Python, it is a python package used for scientific computation. It allows users to perform fast operations related to mathematical functions, arrays, linear algebra, statistics and more. It is an efficient tool for shape manipulation, sorting, and selecting elements. 


### Numpy ndarray

- Numpy ndarray stands for N dimentional array, it is a class of Numpy's array which has attributes such as ndim, shape, size, dtype, itemsize, data
- The elements inside the array are made of the same data type and with the same size in memory
- Numpy array are fixed size when created, if one decided to change the size then a new array is created and the original is  deleted
- It is possible to have arrays of objects, which can be made of different sized elements 



### Creating Array

In [2]:
import numpy as np

In [16]:
a = np.array(range(1,10))
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

### Array Attributes

In [17]:
a.dtype

dtype('int32')

In [18]:
a.size

9

In [19]:
a.ndim

1

In [20]:
a.shape

(9,)

In [7]:
# a[start:stop:step]
# start is the starting index
# stop is stopping index
# step is the step in between, which starts at 1
a[::1]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
a[::2] # Selecting every other element

array([1, 3, 5, 7, 9])

In [17]:
# The elements are reversed, meaning it starts at the end all the way to the first element, 
# Negative indices are interpreted as counting from the end of the array

a[::-1] 

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

In [10]:
a[6::-1] # Starting at 7th element, it goes down by 1

array([7, 6, 5, 4, 3, 2, 1])

In [11]:
a[-3:10] # Starting at the third last element and move up by one 

array([7, 8, 9])

In [12]:
a[-2:4:-1] # Starting at the second last element goes down by one until the fifth element(which is not included)

array([8, 7, 6])

### Slicing Two Dimentional Array

In [16]:
x = np.array([[1,2,3], [4,5,6]])
x

array([[1, 2, 3],
       [4, 5, 6]])